begin;

create table if not exists public.hot_topics (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('baidu', 'weibo', 'toutiao', 'xiaohongshu', 'tencent')),
  external_id text not null,
  title text not null,
  url text not null,
  summary text,
  cover_url text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (source, external_id)
);

create table if not exists public.hot_topic_snapshots (
  id bigint generated by default as identity primary key,
  topic_id bigint not null references public.hot_topics(id) on delete cascade,
  captured_date date not null,
  captured_at timestamptz not null default now(),
  rank smallint not null check (rank > 0),
  hot_score bigint check (hot_score is null or hot_score >= 0),
  unique (topic_id, captured_date)
);

create table if not exists public.collection_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null,
  finished_at timestamptz not null,
  status text not null check (status in ('success', 'partial', 'failed')),
  item_count integer not null default 0,
  source_statuses jsonb not null default '{}'::jsonb,
  error_message text
);

create index if not exists hot_topics_source_idx on public.hot_topics(source);
create index if not exists hot_topics_last_seen_idx on public.hot_topics(last_seen_at desc);
create index if not exists hot_topic_snapshots_date_rank_idx on public.hot_topic_snapshots(captured_date desc, rank);
create index if not exists hot_topic_snapshots_topic_date_idx on public.hot_topic_snapshots(topic_id, captured_date desc);
create index if not exists collection_runs_finished_idx on public.collection_runs(finished_at desc);

alter table public.hot_topics enable row level security;
alter table public.hot_topic_snapshots enable row level security;
alter table public.collection_runs enable row level security;

revoke all on table public.hot_topics from anon, authenticated;
revoke all on table public.hot_topic_snapshots from anon, authenticated;
revoke all on table public.collection_runs from anon, authenticated;

create or replace function public.get_hot_topics(
  p_date date,
  p_source text default null,
  p_limit integer default 100,
  p_offset integer default 0
)
returns table (
  id bigint,
  source text,
  title text,
  url text,
  summary text,
  cover_url text,
  rank smallint,
  hot_score bigint,
  captured_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    topic.id,
    topic.source,
    topic.title,
    topic.url,
    topic.summary,
    topic.cover_url,
    snapshot.rank,
    snapshot.hot_score,
    snapshot.captured_at
  from public.hot_topic_snapshots snapshot
  join public.hot_topics topic on topic.id = snapshot.topic_id
  where snapshot.captured_date = p_date
    and (p_source is null or topic.source = p_source)
  order by snapshot.rank asc, snapshot.hot_score desc nulls last, topic.id asc
  limit least(greatest(coalesce(p_limit, 100), 1), 100)
  offset greatest(coalesce(p_offset, 0), 0);
$$;

create or replace function public.get_hot_source_summary(p_date date)
returns table (
  source text,
  item_count integer,
  latest_captured_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    topic.source,
    count(*)::integer as item_count,
    max(snapshot.captured_at) as latest_captured_at
  from public.hot_topic_snapshots snapshot
  join public.hot_topics topic on topic.id = snapshot.topic_id
  where snapshot.captured_date = p_date
  group by topic.source
  order by topic.source;
$$;

revoke all on function public.get_hot_topics(date, text, integer, integer) from public;
revoke all on function public.get_hot_source_summary(date) from public;
grant execute on function public.get_hot_topics(date, text, integer, integer) to anon, authenticated;
grant execute on function public.get_hot_source_summary(date) to anon, authenticated;

commit;
